<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/estilo.css">
</head>
</body>






    <header>
        <div class="container">
            <center>
            <h1>Control-Covid19</h1>
            </center>
            
        </div>
    </header>
    <div class="container">
            <div class="form-group row">
                <div class="col-sm-10">
                
                </div>
            </div>
        </div>
        <div class="container">
        <form>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Documento</label>
                <div class="col-sm-10">
                <input type="text" class="form-control" name="documento" placeholder="Documento:">
                </div>
            </div>

            <fieldset class="form-group">
                <div class="row">
                <legend class="col-form-label col-sm-2 pt-0">Estado</legend>
                <div class="col-sm-10">
                    <div class="form-check">
                    <input class="form-check-input" type="radio" name="estado" id="gridRadios1" value="option1" checked>
                    <label class="form-check-label" for="gridRadios1">
                        Entra
                    </label>
                    </div>
                    <div class="form-check">
                    <input class="form-check-input" type="radio" name="estado" id="gridRadios2" value="option2">
                    <label class="form-check-label" for="gridRadios2">
                        Sale
                    </label>
                    </div>
                
                </div>
                </div>
            </fieldset>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Ubicación</label>
                <div class="col-sm-10">
                <input type="text" class="form-control" placeholder="Ubicación:">
                </div>
            </div>

            <div class="container">
                <div class="form-group row">
                    
                    <button type="submit" class="btn btn-primary col-4">Guardar</button>

                    <input type="button" class="btn btn-success col-4 offset-4" onclick="location.href='visitante.phtml'" value="Agregar">
                </div>
                <div class="form-group row">
                    <input type="button" class="btn btn-danger col-2 offset-5" onclick="location.href='ingreso.phtml'" value="Salir">
                </div>
            </div>
            
                
        </form>
        <br><br>
   
        

    </div>
    <a href="ingreso.phtml">Volver</a>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>
