
<div class="container">
        <center><h2>CLIENTE</h2></center>
    <form>
            <div class="form-row">
               
                <div class="form-group col-md-12">
                    <input type="text" class="form-control" name="nombre" placeholder="Nombre">
                </div>        
            </div>
                <hr>
            <div class="form-row">
                <div class="form-group col-md-4">                   
                    <select class="form-control" id="exampleFormControlSelect1">
                        <option>Tipo de documento</option>
                    </select>
                </div>
                <div class="form-group col-md-8">                   
                    <input type="number" class="form-control" name="documento" placeholder="Documento">
                </div>
            </div>
                <hr>
            <div class="form-row">
                <div class="form-group col-md-8 offset-md-2">
                    <input type="email" class="form-control" name="documento" placeholder="Correo electronico">     

                </div>              
            </div>
        
            <div class="form-row">
                <div class="form-group col-md-8 offset-md-2">
                <input type="password" class="form-control" placeholder="Contraseña">
                <small id="helpId" class="text-muted">* Debe tener mas de 8 carácteres</small>
                </div>
            </div>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <div class="form-group">                       
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>Selecione el Rol</option>
                        </select>
                    </div>
                </div>
               
                <div class="form-group col-md-6">
                   <input type="number" class="form-control" placeholder="Teléfono">
                </div>
            </div>
                <hr>
            
            <button type="submit" class="btn btn-primary  btn-lg btn-block">Registrar</button>
        </form>
        
    </div>
    
