
    <div class="container">
        <center><h2>CURSOS</h2></center>
        <form>
                <div class="form-row">
                   
                    <div class="form-group col-md-4">
                        <label for="ficha" class="sr-only">Ficha curso</label>
                        <input type="number" class="form-control" name="numero curso" placeholder="Ficha curso">
                    </div>
                    <div class="form-group col-md-8">
                        <label for="curso" class="sr-only">Curso</label>
                        <input type="text" class="form-control" name="curso" placeholder="Curso">
                    </div>        
                </div>
                    <hr>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>Nivel del curso</option>
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>Jornada</option>
                        </select>
                    </div>
                </div>
                    
                    <hr>
                
                <button type="submit" class="btn btn-primary  btn-lg btn-block">Guardar</button>
            </form>
            
        </div>
