

        <div class="container">
            <form>
                <h1 class="offset-1">Ingreso</h1>
            <div class="form-group row">
                
                <div class="col-sm-10 offset-1">
                <input type="text" class="form-control" name="documento" placeholder="Documento:">
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-10 offset-1">
                    <select class="form-control" id="exampleFormControlSelect1">
                        <option>Seleccione la ubicación</option>
                        
                    </select>
                </div>
            </div>
                <hr>
            <h1 class="offset-1">Salida</h1>
            <div class="form-group row">
                
                <div class="col-sm-10 offset-1">
                <input type="text" class="form-control" name="documento" placeholder="Documento:">
                </div>
            </div>

            <div class="container">
                <div class="form-group row">
                    
                    <button type="submit" class="btn btn-primary btn-md col-8 offset-2">Registrar</button>

                </div>
                
                
            </div>
            
                
        </form>
        <br><br>
   
        

    </div>
  



