<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/estilo.css">
</head>
<body>

    <header>
        <div class="container">
            <center>
            <h1>Control-Covid19</h1>
            </center>
            
        </div>
    </header>
    <div class="container">
            <center><h2>VISITANTE</h2></center>
        <form>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="id" class="sr-only">Id usuario</label>
                        <input type="number" class="form-control" name="id usuario" placeholder="Id usuario">
                    </div>
                    <div class="form-group col-md-8">
                        <label for="nombre" class="sr-only">Nombre</label>
                        <input type="text" class="form-control" name="nombre" placeholder="Nombre">
                    </div>        
                </div>
                    <hr>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="id tipo documento" class="sr-only">Id tipo documento</label>
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>Tipo de documento</option>
                            <option value="1">Targeta de identidad</option>
                            <option value="2">Cédula</option>
                            <option value="3">Cédula extranjera</option>
                        </select>
                    </div>
                    <div class="form-group col-md-8">
                        <label for="documento" class="sr-only">Documento</label>
                        <input type="text" class="form-control" name="documento" placeholder="Documento">
                    </div>
                </div>
                    <hr>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="id rol" class="sr-only">Id rol</label>
                        <input type="number" class="form-control" name="id rol" placeholder="Id rol">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="id estado" class="sr-only">Id Estado</label>
                        <input type="number" class="form-control" name="id estado" placeholder="Id estado">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="id curso" class="sr-only">Id curso</label>
                        <input type="number" class="form-control" name="id curso" placeholder="Id curso">
                    </div>
                </div>
                    <hr>
                
                
                <input type="button" class="btn btn-primary  btn-lg btn-block" onclick="alert('Se guardó el visitante'), location.href='bitacora.phtml'" value="Guardar">
            </form>
            
        </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>